name: Тестирование

on: 
  push:
    branches:
      - develop
      - master
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        oscript_version: [1.3.0, dev]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    name: Тестирование
    steps:
      - name: Последняя версия проекта
        uses: actions/checkout@v1
      - name: Установка OneScript
        uses: otymko/setup-onescript@master
        with:
          version: ${{ matrix.oscript_version }}
      - name: Загрузка зависимостей
        run: opm install coverage && opm install 1testrunner && opm install asserts && opm install 1bdd && opm install gitrunner
      - name: Запуск тестов
        run: opm run test
